# Generated by Django 3.0.4 on 2020-04-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_video_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='like_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='view_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
