# Generated by Django 3.0.4 on 2020-04-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20200408_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='date_of_upload',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
