# Generated by Django 3.0.4 on 2020-04-08 22:04

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200408_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videofile',
            field=models.FileField(null=True, upload_to=home.models.generated_filename, verbose_name=''),
        ),
    ]
