# Generated by Django 3.0.5 on 2020-05-02 04:00

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20200502_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='country_of_upload',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
