# Generated by Django 3.0.5 on 2020-05-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='videos_skin',
            field=models.CharField(choices=[('standard', 'standard')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Achievements',
        ),
    ]
