# Generated by Django 3.0.5 on 2020-05-10 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20200510_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='videos_skin',
            new_name='video_skin',
        ),
    ]
