# Generated by Django 3.0.5 on 2020-05-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20200510_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_skin',
            field=models.CharField(choices=[('standard', 'Standard'), ('flag_corner', '🇺🇸 Country Flag'), ('fire_emoji', '🔥 Fire Emoji'), ('rainbow_overlay', '🏳️\u200d🌈 Rainbow Overlay ')], default='standard', max_length=50),
        ),
    ]
