# Generated by Django 3.0.5 on 2020-05-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20200517_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
