# Generated by Django 3.0.5 on 2020-06-16 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20200517_0233'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=50)),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Video')),
            ],
        ),
    ]
