# Generated by Django 3.0.5 on 2020-06-18 19:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_videocomments_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocomments',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
