# Generated by Django 3.0.5 on 2020-06-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_videocomments_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocomments',
            name='message',
            field=models.CharField(max_length=150),
        ),
    ]
