# Generated by Django 3.0.4 on 2020-04-19 04:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_link', models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(10)])),
            ],
        ),
    ]
