# Generated by Django 3.0.5 on 2020-06-13 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20200517_0233'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('functions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostVisualization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Video')),
            ],
        ),
        migrations.DeleteModel(
            name='Achievements',
        ),
    ]
